import React, { useEffect, useRef, useState } from 'react';
import { Hash, MessageSquarePlus, Plus, Send, Settings, UserRound, Users, X } from 'lucide-react';
import { fetchApi } from '../../lib/api';
import { useStore } from '../../store';
import { cn } from '../../lib/utils';

export default function InternalChat() {
  const currentUser = useStore(state => state.currentUser)!;
  const [channels, setChannels] = useState<any[]>([]);
  const [users, setUsers] = useState<any[]>([]);
  const [active, setActive] = useState<any>(null);
  const [messages, setMessages] = useState<any[]>([]);
  const [text, setText] = useState('');
  const [createOpen, setCreateOpen] = useState(false);
  const [manageOpen, setManageOpen] = useState(false);
  const [members, setMembers] = useState<any[]>([]);
  const [form, setForm] = useState({ type: 'direct', name: '', description: '', isPrivate: true, memberIds: [] as string[] });
  const endRef = useRef<HTMLDivElement>(null);
  const loadChannels = () => fetchApi('/internal/channels').then((data: any[]) => { setChannels(data); setActive((selected: any) => selected ? data.find(item => item.id === selected.id) || data[0] || null : data[0] || null); });
  useEffect(() => { Promise.all([loadChannels(), fetchApi('/users').then(setUsers)]); }, []);
  useEffect(() => { if (!active) return setMessages([]); Promise.all([fetchApi(`/internal/channels/${active.id}/messages`).then(setMessages), fetchApi(`/internal/channels/${active.id}/read`, { method: 'POST', body: '{}' })]).then(loadChannels); }, [active?.id]);
  useEffect(() => endRef.current?.scrollIntoView({ behavior: 'smooth' }), [messages]);
  const send = async (event: React.FormEvent) => { event.preventDefault(); if (!active || !text.trim()) return; const message = await fetchApi(`/internal/channels/${active.id}/messages`, { method: 'POST', body: JSON.stringify({ text: text.trim() }) }); setMessages(items => [...items, message]); setText(''); loadChannels(); };
  const create = async () => { const channel = await fetchApi('/internal/channels', { method: 'POST', body: JSON.stringify(form) }); setCreateOpen(false); setForm({ type: 'direct', name: '', description: '', isPrivate: true, memberIds: [] }); await loadChannels(); setActive(channel); };
  const openMembers = async () => { setMembers(await fetchApi(`/internal/channels/${active.id}/members`)); setManageOpen(true); };
  const toggleMember = async (userId: string, included: boolean) => { await fetchApi(`/internal/channels/${active.id}/members${included ? `/${userId}` : ''}`, included ? { method: 'DELETE' } : { method: 'POST', body: JSON.stringify({ userId }) }); setMembers(await fetchApi(`/internal/channels/${active.id}/members`)); };

  return <div className="flex h-[calc(100vh-7rem)] min-h-[520px] overflow-hidden rounded-md border border-slate-200 bg-white shadow-sm">
    <aside className="flex w-72 shrink-0 flex-col border-r border-slate-200"><div className="flex items-center justify-between border-b border-slate-200 p-4"><div><h1 className="font-bold text-slate-800">Chat interno</h1><p className="text-[11px] text-slate-500">Colaboracao privada</p></div><button title="Nova conversa ou canal" onClick={() => setCreateOpen(true)} className="rounded p-2 text-slate-600 hover:bg-slate-100"><MessageSquarePlus size={18} /></button></div><div className="flex-1 overflow-y-auto p-2">{channels.map(channel => <button key={channel.id} onClick={() => setActive(channel)} className={cn('mb-1 flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left', active?.id === channel.id ? 'bg-slate-800 text-white' : 'text-slate-700 hover:bg-slate-100')}><span className="shrink-0">{channel.type === 'direct' ? <UserRound size={17} /> : channel.type === 'lead' ? <Users size={17} /> : <Hash size={17} />}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold">{channel.name}</span><span className="block truncate text-[10px] opacity-60">{channel.type === 'lead' ? 'Discussao de lead' : channel.type}</span></span>{channel.unreadCount > 0 && <span className="rounded-full bg-primary-500 px-1.5 py-0.5 text-[10px] font-bold text-white">{channel.unreadCount}</span>}</button>)}{channels.length === 0 && <p className="p-5 text-center text-xs text-slate-400">Nenhuma conversa interna.</p>}</div></aside>
    <section className="flex min-w-0 flex-1 flex-col">{active ? <><header className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><p className="font-bold text-slate-800">{active.name}</p><p className="text-xs text-slate-500">{active.description || 'Somente usuarios autorizados podem acessar.'}</p></div>{currentUser.role !== 'user' && active.type !== 'direct' && <button onClick={openMembers} title="Gerenciar participantes" className="rounded p-2 text-slate-500 hover:bg-slate-100"><Settings size={17} /></button>}</header><div className="flex-1 space-y-3 overflow-y-auto bg-slate-50 p-5">{messages.map(message => <div key={message.id} className={cn('flex', message.sender_id === currentUser.id ? 'justify-end' : 'justify-start')}><div className={cn('max-w-[70%] rounded-md px-3 py-2', message.sender_id === currentUser.id ? 'bg-slate-800 text-white' : message.mentioned_me ? 'border border-amber-300 bg-amber-50 text-slate-800' : 'bg-white text-slate-800 shadow-sm')}><p className="text-[10px] font-bold opacity-60">{message.sender_name}</p><p className="whitespace-pre-wrap text-sm">{message.text}</p><p className="mt-1 text-[9px] opacity-50">{new Date(message.created_at).toLocaleString()}</p></div></div>)}<div ref={endRef} /></div><form onSubmit={send} className="flex gap-2 border-t border-slate-200 p-4"><textarea value={text} onChange={event => setText(event.target.value)} rows={2} placeholder="Mensagem interna. Use @Nome para mencionar..." className="flex-1 resize-none rounded border border-slate-300 px-3 py-2 text-sm" /><button title="Enviar" disabled={!text.trim()} className="self-end rounded bg-slate-800 p-2.5 text-white disabled:opacity-40"><Send size={17} /></button></form></> : <div className="flex flex-1 items-center justify-center text-sm text-slate-400">Selecione ou crie uma conversa.</div>}</section>
    {createOpen && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/40 p-4"><div className="w-full max-w-lg rounded-md bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold text-slate-800">Nova conversa interna</h2><button onClick={() => setCreateOpen(false)}><X size={19} /></button></div><div className="mt-4 space-y-3"><label className="block text-xs font-bold text-slate-600">Tipo<select value={form.type} onChange={event => setForm({ ...form, type: event.target.value, memberIds: [] })} className="mt-1 w-full rounded border border-slate-300 p-2 font-normal"><option value="direct">Conversa direta</option>{currentUser.role !== 'user' && <><option value="group">Grupo privado</option><option value="company">Canal da empresa</option></>}</select></label>{form.type !== 'direct' && <><label className="block text-xs font-bold text-slate-600">Nome<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="mt-1 w-full rounded border border-slate-300 p-2 font-normal" /></label><label className="block text-xs font-bold text-slate-600">Descricao<input value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} className="mt-1 w-full rounded border border-slate-300 p-2 font-normal" /></label><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={form.isPrivate} onChange={event => setForm({ ...form, isPrivate: event.target.checked })} /> Canal privado</label></>}<div><p className="text-xs font-bold text-slate-600">Participantes</p><div className="mt-2 max-h-52 space-y-1 overflow-y-auto rounded border border-slate-200 p-2">{users.filter(user => user.id !== currentUser.id).map(user => <label key={user.id} className="flex items-center gap-2 rounded p-2 text-sm hover:bg-slate-50"><input type={form.type === 'direct' ? 'radio' : 'checkbox'} checked={form.memberIds.includes(user.id)} onChange={event => setForm({ ...form, memberIds: form.type === 'direct' ? [user.id] : event.target.checked ? [...form.memberIds, user.id] : form.memberIds.filter(id => id !== user.id) })} />{user.name}<span className="text-xs text-slate-400">{user.role}</span></label>)}</div></div></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setCreateOpen(false)} className="px-3 py-2 text-sm text-slate-600">Cancelar</button><button onClick={create} disabled={(form.type === 'direct' && form.memberIds.length !== 1) || (form.type !== 'direct' && !form.name.trim())} className="flex items-center gap-1.5 rounded bg-slate-800 px-3 py-2 text-sm font-bold text-white disabled:opacity-40"><Plus size={15} /> Criar</button></div></div></div>}
    {manageOpen && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-900/40 p-4"><div className="w-full max-w-md rounded-md bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-800">Participantes</h2><p className="text-xs text-slate-500">{active.name}</p></div><button onClick={() => setManageOpen(false)}><X size={19} /></button></div><div className="mt-4 max-h-80 space-y-1 overflow-y-auto">{users.map(user => { const included = members.some(member => member.id === user.id); const owner = members.some(member => member.id === user.id && member.member_role === 'owner'); return <label key={user.id} className="flex items-center gap-2 rounded p-2 text-sm hover:bg-slate-50"><input type="checkbox" checked={included} disabled={owner} onChange={() => toggleMember(user.id, included)} /><span className="flex-1">{user.name}</span><span className="text-[10px] uppercase text-slate-400">{owner ? 'proprietario' : user.role}</span></label>; })}</div><div className="mt-4 flex justify-end"><button onClick={() => setManageOpen(false)} className="rounded bg-slate-800 px-3 py-2 text-sm font-bold text-white">Concluir</button></div></div></div>}
  </div>;
}
